[connection.snowflake]
user = "caiovg91"
password = "@Eclipse18071991"
account = "GPFQBWR-AOB07848"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
role = "SYSADMIN"
client_session_keep_alive = true
